Testcases added to support better test coverage
More testcases have been added for registering and
enrolling a user, and also for util functions to provide
better test coverage. Make file now checks to see
if there is 75% test coverage for each package. If not,
it will return appropriate message.

Code was also reorganized and directory structure was changed.
Filenames all use lowercasing now.

https://jira.hyperledger.org/browse/FAB-862

Change-Id: I82c0265fd3a2bbae4c2b9f2145234db818cbb8cb
Signed-off-by: Saad Karim <skarim@us.ibm.com>

diff --git a/scripts/bash_profile b/scripts/bash_profile
--- a/scripts/bash_profile
+++ b/scripts/bash_profile
@@ -1,9 +1,11 @@
+#!/bin/bash
+
 # This file contains useful functions for fabric development.
 # Modify the following environment variables as desired.
 # The remaining variables should not need to be change.
 # LFID        : your Linux Foundation ID
 # REPO        : your repository name
-export LFID=YOUR-LINUX-FOUNDATION-ID  
+export LFID=YOUR-LINUX-FOUNDATION-ID
 export REPO=fabric-cop
 
 export PROJECT=github.com/hyperledger
@@ -42,7 +44,7 @@ function clonedir {
      echo "Usage: clonedir <dir>"
      return 1
   fi
-  if [ -d $1 ]; then 
+  if [ -d $1 ]; then
      echo "directory $1 already exists"
      return 1
   fi
@@ -74,11 +76,17 @@ function branch {
 
 # push changes to repo
 function push {
-  cdr
-  if [ $? -ne 0 ]; then
-    return 1
-  fi
-  git push origin HEAD:refs/for/master
+ cdr
+ if [ $? -ne 0 ]; then
+   return 1
+ fi
+ echo "Running make before pushing ..."
+ make
+ if [ $? -ne 0 ]; then
+   echo "Not pushing because make failed"
+   return 1
+ fi
+ git push origin HEAD:refs/for/master
 }
 
 # Rebase your current branch on the latest from master
@@ -95,7 +103,7 @@ function rebase {
       return 1
    fi
    echo "Updating master ..."
-   git pull   
+   git pull
    if [ $? -ne 0 ]; then
       echo "Failed to pull from master"
       return 1
@@ -150,4 +158,8 @@ function cdr {
 function initvars {
    export PROJECT_DIR=$GOPATH/src/$PROJECT
    export REPO_DIR=$PROJECT_DIR/$REPO
+}
+
+function coverage {
+   gocov test `go list ./... | grep -v "/vendor/"` | gocov-html > /tmp/coverage.html
 }
