[FAB-3924] Improve test coverage of lib
This change set improves the coverage of the
lib package to over 85%. Most of the changes
are to test files.

The changes to none test files are either improvments
to debug/error messages or the removal of code that
was no longer being used. All of which help to
improve test coverage.

Change-Id: I91816df990ac446182118c67f0de18440805ad5c
Signed-off-by: Keith Smith <bksmith@us.ibm.com>
Signed-off-by: rennman <eabailey@us.ibm.com>
Signed-off-by: Saad Karim <skarim@us.ibm.com>

diff --git a/scripts/check_imports b/scripts/check_imports
--- a/scripts/check_imports
+++ b/scripts/check_imports
@@ -4,13 +4,20 @@
 #
 # SPDX-License-Identifier: Apache-2.0
 #
-if [ ! -f $GOPATH/bin/goimports ]; then
+
+GOIMPORTS="$GOPATH/bin/goimports"
+
+if [ ! -f $GOIMPORTS ]; then
    echo "Installing goimports ..."
    go get golang.org/x/tools/cmd/goimports
+   if [ $? -ne 0 ]; then
+      echo "Failed to install goimports"
+      exit 1
+   fi
 fi
 
 echo "Checking imports ..."
-found=`goimports -l \`find . -name "*.go" |grep -v "./vendor"\` 2>&1`
+found=`$GOIMPORTS -l \`find . -name "*.go" |grep -v "./vendor"\` 2>&1`
 if [ "$found" != "" ]; then
    echo "The following files have import problems:"
    echo "$found"
